### ISSUE TITLE
Quote Report / Text for optionele producten should be Abonnementen 

### ISSUE THREAD

**Issue by timsmet** [timsmet/odoodc#11]
Is it possible to add those changes to the customer module ?

**Comment by rjpathan** [comment]
Please confirm in which part of the customer module to change.

Also, I have updated translation for language **German/Deutsch** with code **de**
But it seems on Test_reports build, language installed are **Dutch/Nederlands** (nl) and **Dutch(BE) / Nederlands(BE)** (nl_BE)
