### ISSUE TITLE
All reports / Check why only the street of the address is used and not the city information 

### ISSUE THREAD

**Issue by timsmet** [timsmet/odoodc#21]
![image](https://user-images.githubusercontent.com/34832587/47991359-39b60780-e0ea-11e8-8c01-17d08bdd24a1.png)

**Comment by rjpathan** [comment]
Fixed https://github.com/timsmet/odoodc/commit/a36f52fd657dac64a8ffd399c52d27158903f56e

Company address information is defined in report files (instead of fetching from system). Please confirm if this must take from the system and not hard coded.

**Comment by timsmet** [comment]
No can be hard coded but the address should be complete

**Comment by rjpathan** [comment]
Ok, for now it has been hard coded in the report view and if needed we can change the same in the view.
