### ISSUE TITLE
Quote / When quote is sent by email it uses default report from odoo 

### ISSUE THREAD

**Issue by timsmet** [timsmet/odoodc#23]
This should be the new report. 
Maybe we could disable the odoo reports all together  ?

**Comment by rjpathan** [comment]
Fixed
1) Print button click to download custom report - https://github.com/timsmet/odoodc/commit/e9608a6b41995d751b1829216ee02b958f974fbe
2) Set custom report as an attachment for Send By Email Template - https://github.com/timsmet/odoodc/commit/c6dae127a7fd3add04dd870a5f966dbc7e5cb097
