### ISSUE TITLE
Invoice report / Remove customer number - make to box in one line ... 

### ISSUE THREAD

**Issue by timsmet** [timsmet/odoodc#24]

**Comment by rjpathan** [comment]
Fixed https://github.com/timsmet/odoodc/commit/e6468471f0a9810f13458555a5a3187f5473517f

![image](https://user-images.githubusercontent.com/6248084/48109200-76aa0780-e26c-11e8-81b0-f5430505896c.png)

**Comment by timsmet** [comment]
Translations are missing

**Comment by rjpathan** [comment]
Translation updated https://github.com/timsmet/odoodc/commit/4dbf94c0726fd0c5e0bb943b1278b1cc49303a64
