### ISSUE TITLE
Quote Report / Could we add a space between the TotalEUR (2 times)

### ISSUE THREAD

**Issue by timsmet** [timsmet/odoodc#6]

**Comment by rjpathan** [comment]
Fixed https://github.com/timsmet/odoodc/commit/9265f83d9a27b54b665d094c9c3860c0a7b9e1e7

**Comment by rjpathan** [comment]
Fixed https://github.com/timsmet/odoodc/commit/9265f83d9a27b54b665d094c9c3860c0a7b9e1e7
