### ISSUE TITLE
Quote Report / Remove the fax number 

### ISSUE THREAD

**Issue by timsmet** [timsmet/odoodc#7]
Nobody uses fax numbers anymore ... 

Maybe the blue box could be redesigned into one line so we save some space on the report

**Comment by rjpathan** [comment]
Fixed https://github.com/timsmet/odoodc/commit/ed02297a2c10485fe3f0388e9c9118a02814523f
![image](https://user-images.githubusercontent.com/6248084/48108965-9260de00-e26b-11e8-9b17-865985273db0.png)

**Comment by rjpathan** [comment]
Last column shows label **Quote No** or **Order No** based on Status.

**Comment by timsmet** [comment]
Translations are missing ?

**Comment by rjpathan** [comment]
Translation updated https://github.com/timsmet/odoodc/commit/9cb581821c1c45fa358b188c50efac914a8c13cb https://github.com/timsmet/odoodc/commit/4a136ea3dac22e8d91cc8d77fc1736e648de63c1
